sonar.organization=poun-2108
sonar.projectKey=poun-2108_skillhub-back
sonar.projectName=SkillHub — Backend Laravel

sonar.sources=app
sonar.tests=tests

sonar.php.coverage.reportPaths=coverage.xml

sonar.exclusions=\
  **/vendor/**,\
  **/bootstrap/cache/**,\
  **/storage/**,\
  **/public/**,\
  **/resources/views/**

sonar.coverage.exclusions=\
  app/Models/ActivityLog.php,\
  app/Services/ActivityLogService.php

sonar.sourceEncoding=UTF-8
